### ISSUE TITLE
Transfer repo to a personal account?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/UntweetdAus#2]
@peggynewman :wave: according to our [recently created package curation policy](https://devguide.ropensci.org/curationpolicy.html#incubator-packages) this repo should now be transferred to either one of your personal accounts, or the ropensci-archive organization.

If you don't answer within one month, I'll transfer the repository to ropensci-archive, after which you could still email me to transfer the repo to a personal account.

Thank you!

**Comment by peggynewman** [comment]
HI @maelle happy to have it transferred over to me. Do you initiate that or should I?

**Comment by maelle** [comment]
@peggynewman :wave:! You'll first need to delete your fork of this repository, please ping me once you've done it, then I'll request a transfer to your account.

**Comment by maelle** [comment]
@peggynewman are you still happy to have it transferred over to your account? If so please delete your fork, I can't request the transfer otherwise.

**Comment by maelle** [comment]
Please email me at maelle at ropensci dot org if I should undo the archival. Thank you!
